### ISSUE TITLE
Cloudwatch get_metric_data: "statistic" argument not marked as required

### ISSUE THREAD

**Issue by mcastellin** [chaostoolkit-incubator/chaostoolkit-aws#129]
Hi, I've been toying around with chaostoolkit-aws today and when I configured a `get_metric_data` function for the cloudwatch probe, filled out all required inputs but still got this error:

```
[2021-12-10 23:29:56 ERROR]   => failed: botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter MetricDataQueries[0].MetricStat.Stat, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

Hence it seems the `statistic` argument is required. Find below an example probe to reproduce the issue:

```yaml
  - name: "Is CPU under 5%"
    type: probe
    tolerance: 
      type: range
      range: [0, 5]
    provider:
      type: python
      module: chaosaws.cloudwatch.probes
      func: get_metric_data
      arguments:
        # statistic: Maximum -- without this it won't work
        namespace: AWS/ECS
        metric_name: CPUUtilization
        dimensions:
        - Name: ClusterName
          Value: ${target_cluster_name}
        - Name: ServiceName
          Value: ${target_service_name}
```
